// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  fifth_section: dynamic(() => import("./FifthSection")),
  second_section: dynamic(() => import("./SecondSection")),
};
